#!/bin/bash

apt-get update
apt-get -y install libpython3.9

mkdir tmp
cd tmp

wget https://github.com/ilaspltd/ILASP-releases/releases/download/v4.3.1/ILASP-4.3.1-ubuntu.tar.gz
tar -xzf ILASP-4.3.1-ubuntu.tar.gz
mv ./ILASP /usr/local/bin/ILASP
cd ../
rm -rf ./tmp
